# Generated by Django 3.2.1 on 2021-05-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Course title')),
                ('date_start', models.DateField(verbose_name='Start date of course')),
                ('date_end', models.DateField(verbose_name='End date of course')),
                ('count_lectures', models.PositiveIntegerField(verbose_name='Lectures count')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['id'],
            },
        ),
    ]
